### PR TITLE
added AlexStefan.spec.js

### PR DESCRIPTION
**Pull request by AlexStefan17**
Added AlexStefan.spec.js file with a basic test that opens a website and validates the title

### CODE REVIEW

**Comment by adrianmaciuc** [comment]
Numele la branch uri de obicei cu litere mici

**Comment by adrianmaciuc** [comment]
Sa nu uiți sa adaugi PRul și în proiect. Alegi la Projects

**Comment by AlexStefan17** [comment]
> Sa nu uiți sa adaugi PRul și în proiect. Alegi la Projects

Done, mersi

**Review by RaduMoldovan30 — APPROVED** [review]

**Review by simonleventeattila — APPROVED** [review]
Works :) 

Interesting finding while running locally, the page does not actually load in the playwright UI for me when running your test. Probabaly an issue on my end.
Recording: https://gofile.me/78bfK/VrTvFaJnm

**Comment by AlexStefan17** [comment]
> Works :)
> 
> Interesting finding while running locally, the page does not actually load in the playwright UI for me when running your test. Probabaly an issue on my end. Recording: https://gofile.me/78bfK/VrTvFaJnm

"It works on my computer" :))

**Pull request merged**
